import Vue from 'vue';
import { Button, Menu, Dropdown, Drawer, Select, InputNumber, Form, Cascader, Popconfirm, Empty, Progress, Pagination, Modal, Divider, Space, List, Comment, Tooltip, Collapse, Checkbox, Radio, Layout, PageHeader, Card, Carousel, Calendar, Switch, Icon, Avatar, Row, Col,DatePicker, Input, AutoComplete, Popover, Badge, Breadcrumb  } from 'ant-design-vue';

Vue.use(Button);
Vue.use(Menu);
Vue.use(Layout);
Vue.use(Switch);
Vue.use(Progress);
Vue.use(Icon);
Vue.use(Row);
Vue.use(Col);
Vue.use(Input);
Vue.use(InputNumber);
Vue.use(AutoComplete);
Vue.use(Popover);
Vue.use(Checkbox);
Vue.use(Divider);
Vue.use(Avatar);
Vue.use(Dropdown);
Vue.use(Drawer);
Vue.use(Badge);
Vue.use(Breadcrumb);
Vue.use(Empty);
Vue.use(DatePicker)
Vue.use(PageHeader)
Vue.use(Calendar)
Vue.use(Card)
Vue.use(Carousel)
Vue.use(Radio)
Vue.use(Cascader)
Vue.use(Collapse)
Vue.use(Comment)
Vue.use(Tooltip)
Vue.use(List)
Vue.use(Form)
Vue.use(Space)
Vue.use(Select)
Vue.use(Modal)
Vue.use(Pagination)
Vue.use(Popconfirm)
