import Vue from 'vue';
import { Button, Menu, Dropdown, Drawer, Select, Skeleton, Spin, Statistic, Slider, InputNumber, Form, Cascader, Popconfirm, Empty, Progress, Pagination, Modal, Divider, Space, List, Comment, Tooltip, Collapse, Checkbox, Radio, Layout, PageHeader, Card, Carousel, Calendar, Switch, Icon, Avatar, Row, Col,DatePicker, TimePicker, Input, AutoComplete, Popover, Badge, Breadcrumb, Rate, Result, Table, Upload, message, Tag  } from 'ant-design-vue';

Vue.use(Rate);
Vue.use(Button);
Vue.use(Menu);
Vue.use(Layout);
Vue.use(Switch);
Vue.use(Progress);
Vue.use(Icon);
Vue.use(Row);
Vue.use(Col);
Vue.use(Input);
Vue.use(InputNumber);
Vue.use(AutoComplete);
Vue.use(Popover);
Vue.use(Checkbox);
Vue.use(Divider);
Vue.use(Avatar);
Vue.use(Dropdown);
Vue.use(Drawer);
Vue.use(Badge);
Vue.use(Breadcrumb);
Vue.use(Empty);
Vue.use(Skeleton);
Vue.use(Spin);
Vue.use(Statistic);
Vue.use(Slider);
Vue.use(DatePicker)
Vue.use(TimePicker)
Vue.use(PageHeader)
Vue.use(Calendar)
Vue.use(Card)
Vue.use(Carousel)
Vue.use(Radio)
Vue.use(Cascader)
Vue.use(Collapse)
Vue.use(Comment)
Vue.use(Tooltip)
Vue.use(List)
Vue.use(Form)
Vue.use(Space)
Vue.use(Upload)
Vue.use(Select)
Vue.use(Table)
Vue.use(Modal)
Vue.use(Pagination)
Vue.use(Popconfirm)
Vue.use(Progress)
Vue.use(Result)
Vue.use(message)
Vue.use(Tag)
